# โหลดข้อมูล (Loading data)




## Iris Dataset

ข้อูลที่จะใช้ในตัวอย่างนี้เป็นชุดข้อมู __Iris__ (Iris dataset) ซึ่งเป็นชุดข้อมูลพื้นฐานที่ใช้กันอย่างแพร่หลายในการเรียนรู้เครื่องจักร (Machine Learning) และทางสถิติ (Statistic) หากได้ติดตั้ง __scikit-learn__ จะสามารถโหลดข้อมูลมาใช้งานได้

![alt text](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Machine+Learning+R/iris-machinelearning.png "Iris dataset")

## การโหลดชุดข้อมูล iris จาก scikit-learn สามารถทำได้ 2 วิธี 

In [48]:
# Method 1
from sklearn import datasets

iris_dataset = datasets.load_iris()

In [49]:
# Method 2
from sklearn.datasets import load_iris

iris_dataset = load_iris()

โดยที่ __load_iris()__ เป็นฟังก์ชัน (Function) ที่อยู่ในโมดูล (Module) datasets

ฟังก์ชัน load_iris() จะคืนค่า (return) ออกมาเป็น __Bunch object__ ซึ่งจะมีโครงสร้างคล้าย ๆ กับ __dictionary__ ที่ประกอบด้วย __keys__ และ __values__

In [8]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
['target_names', 'data', 'target', 'DESCR', 'feature_names']


DESCR คือตัวแปรหรือ key ที่ใช้เพื่อเก็บค่า (value) โดยค่านั้นคือรายละเอียดของชุดข้อมูล iris

In [12]:
print(iris_dataset['DESCR'])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

## ลักษณะของข้อมูล

In [29]:
print("Target names: \n{}".format(iris_dataset['target_names']))

Target names: 
['setosa' 'versicolor' 'virginica']


![alt text](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Machine+Learning+R/iris-machinelearning.png "Iris dataset")

In [31]:
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


รายละเอียดของข้อมูล
![alt text](image/iris-flower.png "Iris dataset")

In [39]:
# ตัวอย่างข้อมูล 10 แถวแรก
print("First ten rows of data:\n {}".format(iris_dataset['data'][0:10]))

First ten rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [40]:
# ตัวอย่างผลลัพธ์ หรือ class ของข้อมูล
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


โดย
```
0 หมายถึง iris setosa
1 หมายถึง iris versicolor
2 หมายถึง iris virginica
```

In [42]:
# แสดงจำนวนของผลลัพธ์
print("shape of target: {}".format(iris_dataset['target'].shape))

shape of target: (150,)


In [46]:
# ประเภทข้อมูลของ target
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <type 'numpy.ndarray'>
