In [2]:
import numpy as np
from sklearn.datasets import load_iris

iris_dataset = load_iris()

x = iris_dataset.data   # x = iris_dataset['data']
y = iris_dataset.target # y = iris_dataset['target']

len_y = len(y)
new_y = np.reshape(y,(len_y,1))
dataset = np.append(new_y,x, axis=1)

print(dataset)

[[0.  5.1 3.5 1.4 0.2]
 [0.  4.9 3.  1.4 0.2]
 [0.  4.7 3.2 1.3 0.2]
 [0.  4.6 3.1 1.5 0.2]
 [0.  5.  3.6 1.4 0.2]
 [0.  5.4 3.9 1.7 0.4]
 [0.  4.6 3.4 1.4 0.3]
 [0.  5.  3.4 1.5 0.2]
 [0.  4.4 2.9 1.4 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  5.4 3.7 1.5 0.2]
 [0.  4.8 3.4 1.6 0.2]
 [0.  4.8 3.  1.4 0.1]
 [0.  4.3 3.  1.1 0.1]
 [0.  5.8 4.  1.2 0.2]
 [0.  5.7 4.4 1.5 0.4]
 [0.  5.4 3.9 1.3 0.4]
 [0.  5.1 3.5 1.4 0.3]
 [0.  5.7 3.8 1.7 0.3]
 [0.  5.1 3.8 1.5 0.3]
 [0.  5.4 3.4 1.7 0.2]
 [0.  5.1 3.7 1.5 0.4]
 [0.  4.6 3.6 1.  0.2]
 [0.  5.1 3.3 1.7 0.5]
 [0.  4.8 3.4 1.9 0.2]
 [0.  5.  3.  1.6 0.2]
 [0.  5.  3.4 1.6 0.4]
 [0.  5.2 3.5 1.5 0.2]
 [0.  5.2 3.4 1.4 0.2]
 [0.  4.7 3.2 1.6 0.2]
 [0.  4.8 3.1 1.6 0.2]
 [0.  5.4 3.4 1.5 0.4]
 [0.  5.2 4.1 1.5 0.1]
 [0.  5.5 4.2 1.4 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  5.  3.2 1.2 0.2]
 [0.  5.5 3.5 1.3 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  4.4 3.  1.3 0.2]
 [0.  5.1 3.4 1.5 0.2]
 [0.  5.  3.5 1.3 0.3]
 [0.  4.5 2.3 1.3 0.3]
 [0.  4.4 3.2 1.3 0.2]
 [0.  5.  3

In [3]:
print(dataset[0])

[0.  5.1 3.5 1.4 0.2]


In [4]:
dataset[0][:]

array([0. , 5.1, 3.5, 1.4, 0.2])

In [5]:
dataset[0][0]

0.0

In [6]:
dataset[0][-1]

0.2

In [7]:
dataset[0][0:-1]

array([0. , 5.1, 3.5, 1.4])